#!/usr/bin/env node
/**
 * Prepare current Kimi Code CLI project skills, agents, MCP, and hooks.
 * No home-directory writes unless --install-hooks is explicitly supplied.
 * Runtime: Node 22.6+ with --experimental-strip-types; no dependencies.
 */

import { createHash, randomUUID } from "node:crypto";
import {
	chmodSync,
	copyFileSync,
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	realpathSync,
	renameSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isMainModule } from "../.claude/scripts/lib/main-guard.ts";

type SetupOptions = {
	readonly vaultRoot: string;
	readonly nodePath?: string;
	readonly platform?: NodeJS.Platform;
	readonly installHooks?: boolean;
	readonly kimiHome?: string;
};

type SetupResult = {
	readonly changed: string[];
	readonly conflicts: string[];
	readonly backups: string[];
	readonly hooksPath: string;
	readonly configPath: string | null;
};

type ManagedState = {
	version: 1;
	files: Record<string, string>;
	qmd?: string;
	hookId?: string;
	vaultRoot?: string;
};
const STATE_FILE = ".mind-setup.json";

function digest(value: string | Buffer): string {
	return createHash("sha256").update(value).digest("hex");
}

function readOptional(path: string): string | null {
	try {
		return readFileSync(path, "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
		throw error;
	}
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Shell arguments are never interpolated unquoted (including apostrophes). */
export function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function buildHooks(vaultRoot: string, nodePath: string): string {
	const command = [
		nodePath,
		"--disable-warning=ExperimentalWarning",
		"--experimental-strip-types",
		join(vaultRoot, ".claude/scripts/kimi-hook.ts"),
	]
		.map(shellQuote)
		.join(" ");
	return (
		"# Generated by obsidian-mind. Kimi reads hooks from its USER config.toml.\n" +
		"# Review this file, then run kimi-setup.ts --install-hooks to merge it.\n" +
		["SessionStart", "UserPromptSubmit", "PostToolUse", "Stop", "SessionEnd"]
			.map(
				(event) =>
					`\n[[hooks]]\nevent = ${JSON.stringify(event)}\n` +
					(event === "PostToolUse" ? 'matcher = "^(Write|Edit)$"\n' : "") +
					`command = ${JSON.stringify(command)}\ntimeout = ${event === "UserPromptSubmit" ? 60 : 30}\n`,
			)
			.join("")
	);
}

type TomlLine = { offset: number; raw: string; code: string; comment: number };

/**
 * Locate actual statements/comments without treating multiline strings or
 * array contents as TOML tables, keys, or managed markers. This is a lexer,
 * not a config serializer: all unrelated bytes stay exactly as supplied.
 */
function tomlLines(config: string): TomlLine[] {
	const lines: TomlLine[] = [];
	let quote = "";
	let depth = 0;
	let offset = 0;
	for (const raw of config.match(/[^\n]*\n|[^\n]+$/g) ?? []) {
		const statement = quote === "" && depth === 0;
		let code = "";
		let comment = -1;
		for (let i = 0; i < raw.length; i++) {
			const char = raw[i]!;
			if (quote) {
				code += " ";
				if (quote.startsWith('"') && char === "\\") {
					i++;
					code += " ";
				} else if (quote.length === 3 && raw.startsWith(quote, i)) {
					// TOML permits one/two quotes before a triple-quote terminator.
					let count = 3;
					while (count < 5 && raw[i + count] === quote[0]) count++;
					i += count - 1;
					code += " ".repeat(count - 1);
					quote = "";
				} else if (quote.length === 1 && char === quote) quote = "";
				continue;
			}
			if (char === "#") {
				comment = i;
				break;
			}
			if (char === '"' || char === "'") {
				quote = raw.startsWith(char.repeat(3), i) ? char.repeat(3) : char;
				i += quote.length - 1;
				code += " ".repeat(quote.length);
			} else {
				code += char;
				if (char === "[" || char === "{") depth++;
				else if (char === "]" || char === "}") depth--;
				if (depth < 0) throw new Error("Unbalanced config.toml; existing config was not changed.");
			}
		}
		if (quote.length === 1) throw new Error("Unterminated config.toml string; existing config was not changed.");
		if (statement) lines.push({ offset, raw, code, comment });
		offset += raw.length;
	}
	if (quote || depth !== 0) throw new Error("Unterminated config.toml value; existing config was not changed.");
	return lines;
}

function tomlKey(raw: string): string {
	const key = raw.trim();
	if (key.startsWith("'") && key.endsWith("'")) return key.slice(1, -1);
	if (key.startsWith('"') && key.endsWith('"')) {
		// JSON shares TOML's basic-string escapes except the eight-digit form.
		let json = '"';
		for (let i = 1; i < key.length - 1; i++) {
			if (key[i] === "\\" && key[i + 1] === "U") {
				const hex = key.slice(i + 2, i + 10);
				if (!/^[a-fA-F0-9]{8}$/.test(hex)) throw new Error("Invalid TOML key escape; config was not changed.");
				json += JSON.stringify(String.fromCodePoint(Number.parseInt(hex, 16))).slice(1, -1);
				i += 9;
			} else {
				json += key[i];
				if (key[i] === "\\") json += key[++i];
			}
		}
		return JSON.parse(`${json}"`) as string;
	}
	return key;
}

function removeEmptyRootHooks(config: string, lines: TomlLine[]): string {
	for (const line of lines) {
		if (line.code.trimStart().startsWith("[")) break;
		const equals = line.code.indexOf("=");
		if (equals < 0 || line.code.slice(0, equals).includes(".") || tomlKey(line.raw.slice(0, equals)) !== "hooks") continue;
		const value = line.raw.slice(equals + 1, line.comment < 0 ? undefined : line.comment).trim();
		if (!/^\[[ \t]*\]$/.test(value)) {
			throw new Error("config.toml uses a root hooks = [...] value. Convert it to [[hooks]] tables before --install-hooks; the existing file was not changed.");
		}
		const tail = line.comment >= 0 ? line.raw.slice(line.comment) : (line.raw.match(/\r?\n$/)?.[0] ?? "");
		return config.slice(0, line.offset) + tail + config.slice(line.offset + line.raw.length);
	}
	return config;
}

/** Append only array tables, so a preceding [provider] cannot swallow keys. */
export function mergeHooks(config: string, vaultRoot: string, hooks: string, id = digest(vaultRoot).slice(0, 16)): string {
	if (!/^[a-f0-9]{16}$/.test(id)) throw new Error("Invalid managed hook identifier.");
	const begin = `# BEGIN obsidian-mind hooks ${id}`;
	const end = `# END obsidian-mind hooks ${id}`;
	const block = `${begin}\n# Vault: ${JSON.stringify(vaultRoot)}\n${hooks}${end}\n`;
	const lines = tomlLines(config);
	const starts = lines.filter((line) => line.raw.trim() === begin);
	const ends = lines.filter((line) => line.raw.trim() === end);
	if (starts.length !== ends.length || starts.length > 1) {
		throw new Error("Ambiguous obsidian-mind hook markers; config.toml was not changed.");
	}
	if (starts.length === 1 && ends.length === 1) {
		const start = starts[0]!.offset;
		const ending = ends[0]!;
		if (ending.offset < start) throw new Error("Reversed obsidian-mind hook markers; config.toml was not changed.");
		if (lines.some((line) => line.offset > start && line.offset < ending.offset && /^# (?:BEGIN|END) obsidian-mind hooks /.test(line.raw.trimStart()))) {
			throw new Error("Nested obsidian-mind hook markers; config.toml was not changed.");
		}
		return config.slice(0, start) + block + config.slice(ending.offset + ending.raw.length);
	}
	const prefix = removeEmptyRootHooks(config, lines);
	return prefix + (prefix === "" ? "" : prefix.endsWith("\n") ? "\n" : "\n\n") + block;
}

function backup(path: string, result: SetupResult): void {
	const backupPath = `${path}.bak-${new Date().toISOString().replaceAll(":", "-")}-${randomUUID().slice(0, 8)}`;
	copyFileSync(path, backupPath);
	result.backups.push(backupPath);
}

/**
 * Replace only after the whole new file exists. Respect intentional global
 * config symlinks, retain file modes, and avoid changing other hard links.
 */
function atomicFile(path: string, write: (temporary: string, mode: number) => void): void {
	let target = path;
	let mode = 0o600;
	let existing = false;
	try {
		const stat = lstatSync(path);
		if (stat.isSymbolicLink()) target = realpathSync(path);
		mode = statSync(target).mode & 0o777;
		existing = true;
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
		// A dangling symlink is not an absent file we own.
		try {
			if (lstatSync(path).isSymbolicLink()) throw new Error(`Refusing dangling config symlink: ${path}`);
		} catch (nested) {
			if ((nested as NodeJS.ErrnoException).code !== "ENOENT") throw nested;
		}
	}
	const temporary = `${target}.tmp-${randomUUID()}`;
	try {
		write(temporary, mode);
		if (existing) chmodSync(temporary, mode); // Creation mode alone is filtered by umask.
		renameSync(temporary, target);
	} finally {
		try { unlinkSync(temporary); } catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
		}
	}
}

function writeChanged(path: string, value: string, result: SetupResult, makeBackup = false): void {
	const previous = readOptional(path);
	if (previous === value) return;
	if (makeBackup && previous !== null) backup(path, result);
	atomicFile(path, (temporary, mode) => writeFileSync(temporary, value, { mode, flag: "wx" }));
	result.changed.push(path);
}

/** Refuse destination symlinks rather than writing into a user's other tree. */
function safeParents(root: string, relative: string): boolean {
	let path = root;
	for (const part of relative.split("/").slice(0, -1)) {
		path = join(path, part);
		try {
			const stat = lstatSync(path);
			if (!stat.isDirectory() || stat.isSymbolicLink()) return false;
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
			mkdirSync(path);
		}
	}
	return true;
}

function readState(path: string): ManagedState {
	const raw = readOptional(path);
	if (raw === null) return { version: 1, files: {} };
	const state: unknown = JSON.parse(raw);
	if (!isRecord(state) || state.version !== 1 || !isRecord(state.files) ||
		!Object.keys(state.files).every((file) => /^(skills|agents)\//.test(file) && !file.includes("\\") && file.split("/").every((part) => part !== "" && part !== "." && part !== ".." && !part.includes("\0"))) ||
		!Object.values(state.files).every((hash) => typeof hash === "string" && /^[a-f0-9]{64}$/.test(hash)) ||
		(state.qmd !== undefined && (typeof state.qmd !== "string" || !/^[a-f0-9]{64}$/.test(state.qmd))) ||
		(state.hookId !== undefined && (typeof state.hookId !== "string" || !/^[a-f0-9]{16}$/.test(state.hookId))) ||
		(state.vaultRoot !== undefined && (typeof state.vaultRoot !== "string" || !isAbsolute(state.vaultRoot)))) {
		throw new Error(`Invalid setup state: ${path}. Preserved it without overwriting generated files.`);
	}
	return state as ManagedState;
}

function previousRoot(state: ManagedState, mcpPath: string, config: string | null): string | null {
	if (state.vaultRoot) return state.vaultRoot;
	// Migrate older state using only MCP metadata that we still own.
	const mcp: unknown = JSON.parse(readOptional(mcpPath) ?? "{}");
	if (isRecord(mcp) && isRecord(mcp.mcpServers) && isRecord(mcp.mcpServers.qmd)) {
		const qmd = mcp.mcpServers.qmd;
		if (state.qmd === digest(JSON.stringify(qmd)) && isRecord(qmd.env) && typeof qmd.env.CLAUDE_PROJECT_DIR === "string" && isAbsolute(qmd.env.CLAUDE_PROJECT_DIR)) return qmd.env.CLAUDE_PROJECT_DIR;
	}
	if (config !== null && state.hookId) {
		const lines = tomlLines(config);
		const start = lines.findIndex((line) => line.raw.trim() === `# BEGIN obsidian-mind hooks ${state.hookId}`);
		const metadata = start < 0 ? undefined : lines[start + 1]?.raw.trim().match(/^# Vault: (.*)$/)?.[1];
		if (metadata) {
			try {
				const path: unknown = JSON.parse(metadata);
				if (typeof path === "string" && isAbsolute(path)) return path;
			} catch { /* Unknown legacy metadata is handled conservatively below. */ }
		}
	}
	return null;
}

function bindHookIdentity(state: ManagedState, vaultRoot: string, oldRoot: string | null): void {
	if (!state.hookId) state.hookId = digest(vaultRoot).slice(0, 16);
	else if (oldRoot === null) {
		// With no trustworthy origin, never replace a potentially unrelated
		// installation. An older orphaned global block can be removed manually.
		state.hookId = randomUUID().replaceAll("-", "").slice(0, 16);
	} else if (oldRoot !== vaultRoot) {
		const raw = readOptional(join(oldRoot, ".kimi-code", STATE_FILE));
		let oldState: unknown = null;
		try { oldState = raw === null ? null : JSON.parse(raw); } catch { /* Unrelated old folder. */ }
		if (isRecord(oldState) && oldState.hookId === state.hookId) {
			// The original still owns this identity: this is a copy, not a move.
			state.hookId = randomUUID().replaceAll("-", "").slice(0, 16);
		}
	}
	state.vaultRoot = vaultRoot;
}

function copyManaged(source: string, relative: string, root: string, state: ManagedState, result: SetupResult): void {
	const path = join(root, relative);
	if (!safeParents(root, relative)) {
		result.conflicts.push(path);
		return;
	}
	const value = readFileSync(source);
	let existing: Buffer | null = null;
	try {
		const stat = lstatSync(path);
		if (!stat.isFile() || stat.isSymbolicLink()) {
			result.conflicts.push(path);
			return;
		}
		existing = readFileSync(path);
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
	}
	if (existing !== null && digest(existing) !== state.files[relative]) {
		result.conflicts.push(path);
		return;
	}
	if (existing === null || !existing.equals(value)) {
		atomicFile(path, (temporary) => copyFileSync(source, temporary));
		result.changed.push(path);
	}
	state.files[relative] = digest(value);
}

function retainManagedTree(relative: string, state: ManagedState, current: Set<string>): boolean {
	let retained = false;
	for (const file of Object.keys(state.files)) {
		if (file === relative || file.startsWith(`${relative}/`)) {
			current.add(file);
			retained = true;
		}
	}
	return retained;
}

function copyTree(source: string, relative: string, root: string, state: ManagedState, result: SetupResult, current: Set<string>): void {
	current.add(relative); // Preserve an old file when its source became a directory.
	for (const entry of readdirSync(source, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
		const child = join(source, entry.name);
		const target = `${relative}/${entry.name}`;
		if (entry.isDirectory()) copyTree(child, target, root, state, result, current);
		else if (entry.isFile()) {
			current.add(target);
			retainManagedTree(target, state, current);
			copyManaged(child, target, root, state, result);
		} else {
			result.conflicts.push(child); // Source symlinks are never followed.
			retainManagedTree(target, state, current);
		}
	}
}

/** Retire only unchanged files we own, without following links or recreating missing parents. */
function retireManagedFiles(root: string, state: ManagedState, current: Set<string>, result: SetupResult): void {
	for (const [relative, hash] of Object.entries(state.files)) {
		if (current.has(relative)) continue;
		const parts = relative.split("/");
		let path = root;
		let missing = false;
		let blocked = false;
		for (let index = 0; index < parts.length; index++) {
			path = join(path, parts[index]!);
			try {
				const stat = lstatSync(path);
				if (stat.isSymbolicLink() || (index === parts.length - 1 ? !stat.isFile() : !stat.isDirectory())) {
					blocked = true;
					break;
				}
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
				missing = true;
				break;
			}
		}
		if (blocked || (!missing && digest(readFileSync(path)) !== hash)) {
			result.conflicts.push(join(root, relative));
			continue;
		}
		if (!missing) {
			unlinkSync(path);
			result.changed.push(path);
		}
		// Keep failed removals owned so a subsequent setup can retry them.
		delete state.files[relative];
	}
}

function planMcp(path: string, vaultRoot: string, nodePath: string, state: ManagedState, result: SetupResult): { content: string; hash: string } | null {
	const previous = readOptional(path);
	const config: unknown = previous === null ? {} : JSON.parse(previous);
	if (!isRecord(config) || (config.mcpServers !== undefined && !isRecord(config.mcpServers))) {
		throw new Error(`Invalid MCP configuration, left unchanged: ${path}`);
	}
	const servers = (config.mcpServers ?? {}) as Record<string, unknown>;
	const qmd = {
		command: nodePath,
		args: [join(vaultRoot, ".claude/scripts/qmd-mcp.mjs")],
		env: { CLAUDE_PROJECT_DIR: vaultRoot },
	};
	if (Object.hasOwn(servers, "qmd")) {
		const existing = JSON.stringify(servers.qmd);
		if (existing === JSON.stringify(qmd)) return null;
		if (state.qmd !== digest(existing)) {
			result.conflicts.push(`${path} (existing qmd server)`);
			return null;
		}
	}
	servers.qmd = qmd;
	config.mcpServers = servers;
	return { content: `${JSON.stringify(config, null, 2)}\n`, hash: digest(JSON.stringify(qmd)) };
}

export function setupKimi(options: SetupOptions): SetupResult {
	if ((options.platform ?? process.platform) === "win32") {
		throw new Error("Kimi hook setup currently supports macOS/Linux shells. Run it in WSL; native Windows hook commands are not generated.");
	}
	const vaultRoot = realpathSync(options.vaultRoot);
	const nodePath = resolve(options.nodePath ?? process.execPath);
	for (const directory of [".claude", ".claude/skills", ".claude/commands", ".claude/agents"]) {
		const path = join(vaultRoot, directory);
		const stat = lstatSync(path);
		if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error(`Source directory must not be a symbolic link: ${path}`);
	}
	for (const required of ["vault-manifest.json", ".claude/scripts/kimi-hook.ts", ".claude/scripts/qmd-mcp.mjs"]) {
		if (!existsSync(join(vaultRoot, required))) throw new Error(`Missing ${required}; run setup in an obsidian-mind checkout with Kimi support.`);
	}
	if (!safeParents(vaultRoot, ".kimi-code/placeholder")) throw new Error(".kimi-code must be a directory, not a symbolic link.");
	const root = join(vaultRoot, ".kimi-code");
	for (const file of [STATE_FILE, "hooks.toml", "mcp.json"]) {
		try {
			if (!lstatSync(join(root, file)).isFile() || lstatSync(join(root, file)).isSymbolicLink()) {
				throw new Error(`Refusing to overwrite non-regular file: ${join(root, file)}`);
			}
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
		}
	}
	const state = readState(join(root, STATE_FILE));
	const result: SetupResult = { changed: [], conflicts: [], backups: [], hooksPath: join(root, "hooks.toml"), configPath: options.installHooks ? join(resolve(options.kimiHome || process.env.KIMI_CODE_HOME || join(homedir(), ".kimi-code")), "config.toml") : null };
	const hooks = buildHooks(vaultRoot, nodePath);
	const mcpPath = join(root, "mcp.json");
	const mcp = planMcp(mcpPath, vaultRoot, nodePath, state, result);
	const originalConfig = result.configPath === null ? null : (readOptional(result.configPath) ?? "");
	bindHookIdentity(state, vaultRoot, previousRoot(state, mcpPath, originalConfig));
	const config = originalConfig === null ? null : mergeHooks(originalConfig, vaultRoot, hooks, state.hookId);
	const skills = join(vaultRoot, ".claude/skills");
	const current = new Set<string>();
	// All config parsing happens above, before changing skills or their hashes.
	// Persist successful copies even if a later filesystem operation fails.
	try {
		for (const entry of readdirSync(skills, { withFileTypes: true })) {
			if (entry.isDirectory()) {
				try { lstatSync(join(skills, entry.name, "SKILL.md")); } catch (error) {
					if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
					throw error;
				}
				copyTree(join(skills, entry.name), `skills/${entry.name}`, root, state, result, current);
			} else {
				const retained = retainManagedTree(`skills/${entry.name}`, state, current);
				if (entry.isSymbolicLink() || retained) result.conflicts.push(join(skills, entry.name));
			}
		}
		for (const [sourceDir, targetDir] of [["commands", "skills"], ["agents", "agents"]] as const) {
			for (const entry of readdirSync(join(vaultRoot, ".claude", sourceDir), { withFileTypes: true })) {
				if (entry.isFile() && entry.name.endsWith(".md")) {
					current.add(`${targetDir}/${entry.name}`);
					copyManaged(join(vaultRoot, ".claude", sourceDir, entry.name), `${targetDir}/${entry.name}`, root, state, result);
				} else if (entry.name.endsWith(".md")) {
					retainManagedTree(`${targetDir}/${entry.name}`, state, current);
					result.conflicts.push(join(vaultRoot, ".claude", sourceDir, entry.name));
				}
			}
		}
		retireManagedFiles(root, state, current, result);
		writeChanged(result.hooksPath, hooks, result, true);
		if (mcp) {
			writeChanged(mcpPath, mcp.content, result, true);
			state.qmd = mcp.hash;
		}
		if (result.configPath !== null && config !== null) {
			mkdirSync(dirname(result.configPath), { recursive: true });
			writeChanged(result.configPath, config, result, true);
		}
	} finally {
		writeChanged(join(root, STATE_FILE), `${JSON.stringify(state, null, 2)}\n`, result);
	}
	return result;
}

function main(): void {
	const args = process.argv.slice(2);
	if (args.includes("--help")) {
		process.stdout.write("Usage: node --experimental-strip-types .scripts/kimi-setup.ts [--install-hooks]\n\nDefault: prepare project skills, agents, MCP, and a reviewable hooks.toml.\n--install-hooks: also merge this vault's hooks into $KIMI_CODE_HOME/config.toml\n(default ~/.kimi-code/config.toml), backing up an existing config before changes.\n");
		return;
	}
	if (args.some((arg) => arg !== "--install-hooks")) throw new Error("Unknown option. Use --help for usage.");
	const result = setupKimi({ vaultRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."), installHooks: args.includes("--install-hooks") });
	process.stdout.write(`Kimi project setup ready (${result.changed.length} files changed).\n`);
	for (const conflict of result.conflicts) process.stdout.write(`Preserved user file/config: ${conflict}\n`);
	for (const path of result.backups) process.stdout.write(`Backup: ${path}\n`);
	if (result.configPath) process.stdout.write(`Hooks installed in ${result.configPath}. Restart Kimi to load them.\n`);
	else process.stdout.write(`Home config unchanged. Review ${result.hooksPath}, then run:\n  node --experimental-strip-types .scripts/kimi-setup.ts --install-hooks\n`);
	process.stdout.write("Open Kimi in this vault and send a regular message first, then try /skill:om-standup or /skill:om-dump <notes>.\nQMD search requires qmd plus the separate .scripts/qmd-bootstrap.ts setup.\n");
}

if (isMainModule(import.meta.url)) {
	try { main(); } catch (error) {
		process.stderr.write(`Kimi setup: ${error instanceof Error ? error.message : String(error)}\n`);
		process.exitCode = 1;
	}
}
