#!/usr/bin/env node
/**
 * Prepare current Kimi Code CLI project skills, agents, MCP, and hooks.
 * No home-directory writes unless --install-hooks is explicitly supplied.
 * Runtime: Node 22.6+ with --experimental-strip-types; no dependencies.
 */

import { createHash, randomUUID } from "node:crypto";
import {
	copyFileSync,
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	realpathSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isMainModule } from "../.claude/scripts/lib/main-guard.ts";

type SetupOptions = {
	readonly vaultRoot: string;
	readonly nodePath?: string;
	readonly platform?: NodeJS.Platform;
	readonly installHooks?: boolean;
	readonly kimiHome?: string;
};

type SetupResult = {
	readonly changed: string[];
	readonly conflicts: string[];
	readonly backups: string[];
	readonly hooksPath: string;
	readonly configPath: string | null;
};

type ManagedState = {
	version: 1;
	files: Record<string, string>;
	qmd?: string;
	hookId?: string;
};
const STATE_FILE = ".mind-setup.json";

function digest(value: string | Buffer): string {
	return createHash("sha256").update(value).digest("hex");
}

function readOptional(path: string): string | null {
	try {
		return readFileSync(path, "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
		throw error;
	}
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Shell arguments are never interpolated unquoted (including apostrophes). */
export function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function buildHooks(vaultRoot: string, nodePath: string): string {
	const command = [
		nodePath,
		"--disable-warning=ExperimentalWarning",
		"--experimental-strip-types",
		join(vaultRoot, ".claude/scripts/kimi-hook.ts"),
	]
		.map(shellQuote)
		.join(" ");
	return (
		"# Generated by obsidian-mind. Kimi reads hooks from its USER config.toml.\n" +
		"# Review this file, then run kimi-setup.ts --install-hooks to merge it.\n" +
		["SessionStart", "UserPromptSubmit", "PostToolUse", "Stop", "SessionEnd"]
			.map(
				(event) =>
					`\n[[hooks]]\nevent = ${JSON.stringify(event)}\n` +
					(event === "PostToolUse" ? 'matcher = "^(Write|Edit)$"\n' : "") +
					`command = ${JSON.stringify(command)}\ntimeout = ${event === "UserPromptSubmit" ? 60 : 30}\n`,
			)
			.join("")
	);
}

/**
 * TOML cannot append [[hooks]] to a hooks = [...] value. Recognize a root
 * empty-array declaration (including quoted keys); refuse nonempty/complex
 * declarations instead of parsing and rewriting the user's entire config.
 * Nested tables may legitimately have a different key called hooks.
 */
function removeEmptyRootHooks(config: string): string {
	let offset = 0;
	for (const line of config.match(/[^\n]*\n|[^\n]+$/g) ?? []) {
		if (/^[ \t]*\[/.test(line)) break;
		if (/^[ \t]*(?:hooks|"hooks"|'hooks')[ \t]*=/.test(line)) {
			const empty = line.match(
				/^[ \t]*(?:hooks|"hooks"|'hooks')[ \t]*=[ \t]*\[[ \t]*\][ \t]*(#[^\r\n]*)?(\r?\n)?$/,
			);
			if (!empty) {
				throw new Error(
					"config.toml uses a root hooks = [...] value. Convert it to [[hooks]] tables before --install-hooks; the existing file was not changed.",
				);
			}
			return config.slice(0, offset) + (empty[1] ?? "") + (empty[2] ?? "") + config.slice(offset + line.length);
		}
		offset += line.length;
	}
	return config;
}

/** Append only array tables, so a preceding [provider] cannot swallow keys. */
export function mergeHooks(config: string, vaultRoot: string, hooks: string, id = digest(vaultRoot).slice(0, 16)): string {
	if (!/^[a-f0-9]{16}$/.test(id)) throw new Error("Invalid managed hook identifier.");
	const begin = `# BEGIN obsidian-mind hooks ${id}`;
	const end = `# END obsidian-mind hooks ${id}`;
	const block = `${begin}\n# Vault: ${JSON.stringify(vaultRoot)}\n${hooks}${end}\n`;
	const starts = [...config.matchAll(new RegExp(`^${begin}\\r?$`, "gm"))];
	const ends = [...config.matchAll(new RegExp(`^${end}\\r?$`, "gm"))];
	if (starts.length !== ends.length || starts.length > 1) {
		throw new Error("Ambiguous obsidian-mind hook markers; config.toml was not changed.");
	}
	if (starts.length === 1 && ends.length === 1) {
		const start = starts[0]!.index;
		const ending = ends[0]!;
		if (ending.index < start) throw new Error("Reversed obsidian-mind hook markers; config.toml was not changed.");
		const after = ending.index + ending[0].length;
		return config.slice(0, start) + block + config.slice(after + (config[after] === "\n" ? 1 : 0));
	}
	const prefix = removeEmptyRootHooks(config);
	return prefix + (prefix === "" ? "" : prefix.endsWith("\n") ? "\n" : "\n\n") + block;
}

function backup(path: string, result: SetupResult): void {
	const backupPath = `${path}.bak-${new Date().toISOString().replaceAll(":", "-")}-${randomUUID().slice(0, 8)}`;
	copyFileSync(path, backupPath);
	result.backups.push(backupPath);
}

function writeChanged(path: string, value: string, result: SetupResult, makeBackup = false): void {
	const previous = readOptional(path);
	if (previous === value) return;
	if (makeBackup && previous !== null) backup(path, result);
	writeFileSync(path, value, { mode: 0o600 });
	result.changed.push(path);
}

/** Refuse destination symlinks rather than writing into a user's other tree. */
function safeParents(root: string, relative: string): boolean {
	let path = root;
	for (const part of relative.split("/").slice(0, -1)) {
		path = join(path, part);
		try {
			const stat = lstatSync(path);
			if (!stat.isDirectory() || stat.isSymbolicLink()) return false;
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
			mkdirSync(path);
		}
	}
	return true;
}

function readState(path: string): ManagedState {
	const raw = readOptional(path);
	if (raw === null) return { version: 1, files: {} };
	const state: unknown = JSON.parse(raw);
	if (!isRecord(state) || state.version !== 1 || !isRecord(state.files) ||
		!Object.values(state.files).every((hash) => typeof hash === "string" && /^[a-f0-9]{64}$/.test(hash)) ||
		(state.qmd !== undefined && (typeof state.qmd !== "string" || !/^[a-f0-9]{64}$/.test(state.qmd))) ||
		(state.hookId !== undefined && (typeof state.hookId !== "string" || !/^[a-f0-9]{16}$/.test(state.hookId)))) {
		throw new Error(`Invalid setup state: ${path}. Preserved it without overwriting generated files.`);
	}
	return state as ManagedState;
}

function copyManaged(source: string, relative: string, root: string, state: ManagedState, result: SetupResult): void {
	const path = join(root, relative);
	if (!safeParents(root, relative)) {
		result.conflicts.push(path);
		return;
	}
	const value = readFileSync(source);
	let existing: Buffer | null = null;
	try {
		const stat = lstatSync(path);
		if (!stat.isFile() || stat.isSymbolicLink()) {
			result.conflicts.push(path);
			return;
		}
		existing = readFileSync(path);
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
	}
	if (existing !== null && digest(existing) !== state.files[relative]) {
		result.conflicts.push(path);
		return;
	}
	if (existing === null || !existing.equals(value)) {
		copyFileSync(source, path);
		result.changed.push(path);
	}
	state.files[relative] = digest(value);
}

function copyTree(source: string, relative: string, root: string, state: ManagedState, result: SetupResult): void {
	for (const entry of readdirSync(source, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
		const child = join(source, entry.name);
		const target = `${relative}/${entry.name}`;
		if (entry.isDirectory()) copyTree(child, target, root, state, result);
		else if (entry.isFile()) copyManaged(child, target, root, state, result);
		else result.conflicts.push(child); // Source symlinks are never followed.
	}
}

function mergeMcp(path: string, vaultRoot: string, nodePath: string, state: ManagedState, result: SetupResult): void {
	const previous = readOptional(path);
	const config: unknown = previous === null ? {} : JSON.parse(previous);
	if (!isRecord(config) || (config.mcpServers !== undefined && !isRecord(config.mcpServers))) {
		throw new Error(`Invalid MCP configuration, left unchanged: ${path}`);
	}
	const servers = (config.mcpServers ?? {}) as Record<string, unknown>;
	const qmd = {
		command: nodePath,
		args: [join(vaultRoot, ".claude/scripts/qmd-mcp.mjs")],
		env: { CLAUDE_PROJECT_DIR: vaultRoot },
	};
	if (Object.hasOwn(servers, "qmd")) {
		const existing = JSON.stringify(servers.qmd);
		if (existing === JSON.stringify(qmd)) return;
		if (state.qmd !== digest(existing)) {
			result.conflicts.push(`${path} (existing qmd server)`);
			return;
		}
	}
	servers.qmd = qmd;
	config.mcpServers = servers;
	writeChanged(path, `${JSON.stringify(config, null, 2)}\n`, result, true);
	state.qmd = digest(JSON.stringify(qmd));
}

export function setupKimi(options: SetupOptions): SetupResult {
	if ((options.platform ?? process.platform) === "win32") {
		throw new Error("Kimi hook setup currently supports macOS/Linux shells. Run it in WSL; native Windows hook commands are not generated.");
	}
	const vaultRoot = realpathSync(options.vaultRoot);
	const nodePath = resolve(options.nodePath ?? process.execPath);
	for (const required of ["vault-manifest.json", ".claude/scripts/kimi-hook.ts", ".claude/scripts/qmd-mcp.mjs"]) {
		if (!existsSync(join(vaultRoot, required))) throw new Error(`Missing ${required}; run setup in an obsidian-mind checkout with Kimi support.`);
	}
	if (!safeParents(vaultRoot, ".kimi-code/placeholder")) throw new Error(".kimi-code must be a directory, not a symbolic link.");
	const root = join(vaultRoot, ".kimi-code");
	for (const file of [STATE_FILE, "hooks.toml", "mcp.json"]) {
		try {
			if (!lstatSync(join(root, file)).isFile() || lstatSync(join(root, file)).isSymbolicLink()) {
				throw new Error(`Refusing to overwrite non-regular file: ${join(root, file)}`);
			}
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
		}
	}
	const state = readState(join(root, STATE_FILE));
	const result: SetupResult = { changed: [], conflicts: [], backups: [], hooksPath: join(root, "hooks.toml"), configPath: options.installHooks ? join(resolve(options.kimiHome || process.env.KIMI_CODE_HOME || join(homedir(), ".kimi-code")), "config.toml") : null };
	const skills = join(vaultRoot, ".claude/skills");
	for (const entry of readdirSync(skills, { withFileTypes: true })) {
		if (entry.isDirectory() && existsSync(join(skills, entry.name, "SKILL.md"))) {
			copyTree(join(skills, entry.name), `skills/${entry.name}`, root, state, result);
		}
	}
	for (const [sourceDir, targetDir] of [["commands", "skills"], ["agents", "agents"]] as const) {
		for (const entry of readdirSync(join(vaultRoot, ".claude", sourceDir), { withFileTypes: true })) {
			if (entry.isFile() && entry.name.endsWith(".md")) {
				copyManaged(join(vaultRoot, ".claude", sourceDir, entry.name), `${targetDir}/${entry.name}`, root, state, result);
			}
		}
	}
	const hooks = buildHooks(vaultRoot, nodePath);
	writeChanged(result.hooksPath, hooks, result, true);
	mergeMcp(join(root, "mcp.json"), vaultRoot, nodePath, state, result);
	state.hookId ??= digest(vaultRoot).slice(0, 16);
	writeChanged(join(root, STATE_FILE), `${JSON.stringify(state, null, 2)}\n`, result);
	if (result.configPath !== null) {
		const config = readOptional(result.configPath) ?? "";
		const merged = mergeHooks(config, vaultRoot, hooks, state.hookId);
		mkdirSync(dirname(result.configPath), { recursive: true });
		writeChanged(result.configPath, merged, result, true);
	}
	return result;
}

function main(): void {
	const args = process.argv.slice(2);
	if (args.includes("--help")) {
		process.stdout.write("Usage: node --experimental-strip-types .scripts/kimi-setup.ts [--install-hooks]\n\nDefault: prepare project skills, agents, MCP, and a reviewable hooks.toml.\n--install-hooks: also merge this vault's hooks into $KIMI_CODE_HOME/config.toml\n(default ~/.kimi-code/config.toml), backing up an existing config before changes.\n");
		return;
	}
	if (args.some((arg) => arg !== "--install-hooks")) throw new Error("Unknown option. Use --help for usage.");
	const result = setupKimi({ vaultRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."), installHooks: args.includes("--install-hooks") });
	process.stdout.write(`Kimi project setup ready (${result.changed.length} files changed).\n`);
	for (const conflict of result.conflicts) process.stdout.write(`Preserved user file/config: ${conflict}\n`);
	for (const path of result.backups) process.stdout.write(`Backup: ${path}\n`);
	if (result.configPath) process.stdout.write(`Hooks installed in ${result.configPath}. Restart Kimi to load them.\n`);
	else process.stdout.write(`Home config unchanged. Review ${result.hooksPath}, then run:\n  node --experimental-strip-types .scripts/kimi-setup.ts --install-hooks\n`);
	process.stdout.write("Open Kimi in this vault and try /skill:om-standup or /skill:om-dump <notes>.\nQMD search requires qmd plus the separate .scripts/qmd-bootstrap.ts setup.\n");
}

if (isMainModule(import.meta.url)) {
	try { main(); } catch (error) {
		process.stderr.write(`Kimi setup: ${error instanceof Error ? error.message : String(error)}\n`);
		process.exitCode = 1;
	}
}
